import type { QuestionMetadata } from "../types";

export const civicsQuestions: QuestionMetadata[] = [
  {
    id: "icse-9-hc-q-civ-001",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-01", topic: "Our Constitution",
    questionType: "very-short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall the meaning of a constitution.",
    source: "practice", year: null,
    question: "What is a constitution?",
    hints: ["Supreme law."],
    answer: "A constitution is the supreme law of a country that lays down the framework of government and the rights and duties of citizens.",
    explanation: "Definition question - key words: supreme law, framework of government.",
    commonMistake: "Describing it only as a book of laws without mentioning its supremacy.",
  },
  {
    id: "icse-9-hc-q-civ-002",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-01", topic: "Our Constitution",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall the adoption and enforcement dates of the Constitution.",
    source: "practice", year: null,
    question: "When was the Indian Constitution adopted and when did it come into force?",
    hints: ["26 November 1949", "26 January 1950"],
    answer: "Adopted on 26 November 1949; came into force on 26 January 1950.",
    explanation: "Two-date standard question.",
    commonMistake: "Reversing the two dates.",
  },
  {
    id: "icse-9-hc-q-civ-003",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-01", topic: "Our Constitution",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Understand",
    learningObjective: "Explain single citizenship.",
    source: "practice", year: null,
    question: "What is meant by single citizenship?",
    hints: ["One citizenship; no state citizenship."],
    answer: "Every Indian is a citizen of India alone; there is no separate citizenship of any state.",
    explanation: "Promotes unity; contrast with dual citizenship systems.",
    commonMistake: "Confusing single citizenship with single national identity.",
  },
  {
    id: "icse-9-hc-q-civ-004",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-01", topic: "Our Constitution",
    questionType: "short", difficulty: "easy", marks: 3, bloomLevel: "Remember",
    learningObjective: "Name and briefly explain Fundamental Rights.",
    source: "practice", year: null,
    question: "Name any three Fundamental Rights guaranteed by the Constitution.",
    hints: ["Equality, freedom, remedies..."],
    answer: "Any three: Right to Equality; Right to Freedom; Right against Exploitation; Right to Freedom of Religion; Cultural and Educational Rights; Right to Constitutional Remedies.",
    explanation: "Naming three accurately is enough.",
    commonMistake: "Inventing rights that are not in the list.",
  },
  {
    id: "icse-9-hc-q-civ-005",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-01", topic: "Our Constitution",
    questionType: "analytical", difficulty: "medium", marks: 4, bloomLevel: "Analyse",
    learningObjective: "Relate Directive Principles to the welfare state idea.",
    source: "practice", year: null,
    question: "How do the Directive Principles of State Policy help India move towards becoming a welfare state?",
    hints: ["Guidelines; social and economic welfare."],
    answer: "They guide governments to frame policies for social and economic welfare - like equality, livelihood, education and health - which is the essence of a welfare state; though not enforceable in courts, they are fundamental in governance.",
    explanation: "Link directive principles to welfare policies.",
    commonMistake: "Saying they are enforceable like Fundamental Rights.",
  },
  {
    id: "icse-9-hc-q-civ-006",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-02", topic: "Elections",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "State the composition of the Election Commission.",
    source: "practice", year: null,
    question: "Mention the composition of the Election Commission of India.",
    hints: ["CEC + two."],
    answer: "The Chief Election Commissioner and two other Election Commissioners.",
    explanation: "Multi-member body; independent of government control.",
    commonMistake: "Writing only the Chief Election Commissioner.",
  },
  {
    id: "icse-9-hc-q-civ-007",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-02", topic: "Elections",
    questionType: "short", difficulty: "medium", marks: 3, bloomLevel: "Understand",
    learningObjective: "Distinguish direct and indirect elections.",
    source: "practice", year: null,
    question: "Distinguish between direct and indirect elections with one example each.",
    hints: ["Who chooses?", "Examples."],
    answer: "In a direct election voters choose the representative directly (e.g. Lok Sabha); in an indirect election elected representatives choose the office-holder (e.g. the President).",
    explanation: "Two clear contrasts plus examples.",
    commonMistake: "Giving examples without the distinction.",
  },
  {
    id: "icse-9-hc-q-civ-008",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-02", topic: "Elections",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Explain the types of elections.",
    source: "practice", year: null,
    question: "Explain the terms: general election, mid-term election and by-election.",
    hints: ["Full House; early dissolution; single vacancy."],
    answer: "General election: all/most seats filled when a House completes its term or is dissolved; mid-term election: held when a House is dissolved before completing its term; by-election: held to fill a casual vacancy in a single constituency.",
    explanation: "Three definitions with the cause of each.",
    commonMistake: "Confusing mid-term with by-election.",
  },
  {
    id: "icse-9-hc-q-civ-009",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-03", topic: "Local Self Government",
    questionType: "very-short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall the three tiers of Panchayati Raj.",
    source: "practice", year: null,
    question: "Name the three tiers of the Panchayati Raj system.",
    hints: ["Village, block, district."],
    answer: "Gram Panchayat (village), Panchayat Samiti (block) and Zila Parishad (district).",
    explanation: "Order village to district.",
    commonMistake: "Missing one tier or swapping levels.",
  },
  {
    id: "icse-9-hc-q-civ-010",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-03", topic: "Local Self Government",
    questionType: "short", difficulty: "easy", marks: 3, bloomLevel: "Remember",
    learningObjective: "List functions of urban local bodies.",
    source: "practice", year: null,
    question: "State any four functions of a Municipal Corporation.",
    hints: ["Water, roads, health, fire..."],
    answer: "Any four: water supply; roads and street lighting; public health and sanitation; fire services; town planning; schools and libraries.",
    explanation: "Four short, distinct civic functions.",
    commonMistake: "Listing state government functions like police or defence.",
  },
  {
    id: "icse-9-hc-q-civ-011",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-03", topic: "Local Self Government",
    questionType: "long", difficulty: "medium", marks: 6, bloomLevel: "Understand",
    learningObjective: "Describe rural and urban local government comprehensively.",
    source: "practice", year: null,
    question: "Describe the structure of rural and urban local self-government in India, giving two functions of each body.",
    hints: ["Three rural tiers; two urban bodies."],
    answer: "Rural: Gram Panchayat, Panchayat Samiti, Zila Parishad with functions like water supply, roads, education, health. Urban: Municipal Committee and Municipal Corporation with functions like water, sanitation, roads, fire services.",
    explanation: "Structure first, functions next.",
    commonMistake: "Writing only structures without functions.",
  },
  {
    id: "icse-9-hc-q-civ-012",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-03", topic: "Local Self Government",
    questionType: "short", difficulty: "medium", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall the amendments giving constitutional status to local bodies.",
    source: "practice", year: null,
    question: "Which amendments gave constitutional status to rural and urban local bodies?",
    hints: ["73rd and 74th."],
    answer: "The 73rd Amendment (1992) for rural bodies and the 74th Amendment (1992) for urban bodies.",
    explanation: "Both came in 1992.",
    commonMistake: "Swapping the two amendments.",
  },
];