import type { QuestionMetadata } from "../types";

export const historyQuestions: QuestionMetadata[] = [
  {
    id: "icse-9-hc-q-his-001",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-01", topic: "The Harappan Civilisation",
    questionType: "very-short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall sources of the Harappan Civilisation.",
    source: "practice", year: null,
    question: "Name any two sources of information about the Harappan Civilisation.",
    hints: ["Artifacts and structures."],
    answer: "Any two: the Great Bath, Citadel, seals, bearded man statue, dancing girl, dockyard, script.",
    explanation: "Sources are archaeological remains.",
    commonMistake: "Naming other civilisations' features.",
  },
  {
    id: "icse-9-hc-q-his-002",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-01", topic: "The Harappan Civilisation",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Understand",
    learningObjective: "Explain the Citadel.",
    source: "practice", year: null,
    question: "What was the Citadel in a Harappan city?",
    hints: ["Upper fortified part."],
    answer: "The fortified upper part of a Harappan city where important public buildings were situated.",
    explanation: "Contrast with the Lower Town.",
    commonMistake: "Confusing Citadel with the Great Bath.",
  },
  {
    id: "icse-9-hc-q-his-003",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-01", topic: "The Harappan Civilisation",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Describe Harappan urban planning.",
    source: "practice", year: null,
    question: "Describe any four features of Harappan urban planning.",
    hints: ["Citadel, grid, bricks, drains."],
    answer: "Citadel and Lower Town division; grid-pattern streets crossing at right angles; standardised burnt bricks; covered drainage system; Great Bath as public architecture (any four).",
    explanation: "Four features, one line each.",
    commonMistake: "Mixing Harappan and Vedic features.",
  },
  {
    id: "icse-9-hc-q-his-004",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-02", topic: "The Vedic Period",
    questionType: "very-short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Name the Vedas and Epics.",
    source: "practice", year: null,
    question: "Name the four Vedas and the two Epics.",
    hints: ["Four Vedas; two Epics."],
    answer: "Vedas: Rigveda, Samaveda, Yajurveda, Atharvaveda. Epics: Ramayana and Mahabharata.",
    explanation: "Standard recall.",
    commonMistake: "Missing one Veda.",
  },
  {
    id: "icse-9-hc-q-his-005",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-02", topic: "The Vedic Period",
    questionType: "long", difficulty: "medium", marks: 6, bloomLevel: "Analyse",
    learningObjective: "Compare early and later Vedic society.",
    source: "practice", year: null,
    question: "Compare Early Vedic and Later Vedic society under the headings: polity, society, position of women and religion.",
    hints: ["Paired points."],
    answer: "Polity: tribal Rajan with Sabha/Samiti vs. powerful kings with weakened assemblies. Society: flexible varna vs. rigid birth-based varna. Women: participation and education vs. declining status and restrictions. Religion: simple nature worship and yajnas vs. elaborate ritual sacrifices.",
    explanation: "Paired contrast under each heading.",
    commonMistake: "Describing only one phase.",
  },
  {
    id: "icse-9-hc-q-his-006",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-03", topic: "Jainism and Buddhism",
    questionType: "short", difficulty: "easy", marks: 3, bloomLevel: "Remember",
    learningObjective: "Recall the five vows of Jainism.",
    source: "practice", year: null,
    question: "Name the five vows of Jainism.",
    hints: ["Ahimsa first."],
    answer: "Ahimsa (non-violence), satya (truth), asteya (non-stealing), aparigraha (non-possession), brahmacharya (chastity).",
    explanation: "Order ahimsa first.",
    commonMistake: "Missing brahmacharya or aparigraha.",
  },
  {
    id: "icse-9-hc-q-his-007",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-03", topic: "Jainism and Buddhism",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "State the Four Noble Truths.",
    source: "practice", year: null,
    question: "State the Four Noble Truths of Buddhism.",
    hints: ["Suffering; cause; end; path."],
    answer: "1) Suffering exists; 2) desire is the cause of suffering; 3) suffering can be ended; 4) the Eightfold Path leads to the end of suffering.",
    explanation: "Numbered, crisp statements.",
    commonMistake: "Listing the Eightfold Path instead of the Four Truths.",
  },
  {
    id: "icse-9-hc-q-his-008",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-03", topic: "Jainism and Buddhism",
    questionType: "short", difficulty: "medium", marks: 3, bloomLevel: "Understand",
    learningObjective: "Explain causes of the rise of the new religions.",
    source: "practice", year: null,
    question: "Mention any three causes for the rise of Jainism and Buddhism in the 6th century BCE.",
    hints: ["Ritualism; caste; trade.",],
    answer: "Any three: rigid caste system; costly elaborate sacrifices; growth of trade and new social classes; Kshatriya resentment; spirit of questioning in the Upanishads.",
    explanation: "Same causes serve both religions.",
    commonMistake: "Giving religious causes only.",
  },
  {
    id: "icse-9-hc-q-his-009",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-04", topic: "The Mauryan Empire",
    questionType: "very-short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall sources of Mauryan history.",
    source: "practice", year: null,
    question: "Name any two sources of Mauryan history.",
    hints: ["A book and an inscription."],
    answer: "Any two: Arthashastra, Indika, Ashokan edicts, Sanchi Stupa.",
    explanation: "Two texts, one inscription group, one monument.",
    commonMistake: "Attributing Indika to Chanakya.",
  },
  {
    id: "icse-9-hc-q-his-010",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-04", topic: "The Mauryan Empire",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Describe Ashoka's Dhamma.",
    source: "practice", year: null,
    question: "Describe the main features of Ashoka's Dhamma.",
    hints: ["Moral code; officials; edicts."],
    answer: "Dhamma was a code of moral conduct: respect for elders and teachers, ahimsa, tolerance among sects, truthfulness and charity. Ashoka spread it through Dhamma Mahamattas and rock and pillar edicts, and by sending missions abroad.",
    explanation: "Principles + methods of propagation.",
    commonMistake: "Calling Dhamma a new religion.",
  },
  {
    id: "icse-9-hc-q-his-011",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-05", topic: "The Sangam Age",
    questionType: "very-short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Define Sangam.",
    source: "practice", year: null,
    question: "What does the term 'Sangam' mean?",
    hints: ["Assembly."],
    answer: "Sangam means an assembly of Tamil poets and scholars; three such assemblies were held at Madurai under Pandya patronage.",
    explanation: "Define + one line of context.",
    commonMistake: "Describing Sangam as a kingdom.",
  },
  {
    id: "icse-9-hc-q-his-012",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-06", topic: "The Age of the Guptas",
    questionType: "short", difficulty: "easy", marks: 3, bloomLevel: "Remember",
    learningObjective: "Recall Gupta educational achievements.",
    source: "practice", year: null,
    question: "What was Nalanda University? Mention any two of its features.",
    hints: ["Centre of learning; foreign students."],
    answer: "Nalanda was a great centre of higher learning in the Gupta period. Features: attracted students from China and other countries; taught Buddhist texts, logic, grammar, medicine and astronomy; supported by kings.",
    explanation: "Identify + two features.",
    commonMistake: "Calling Nalanda a Mauryan foundation.",
  },
  {
    id: "icse-9-hc-q-his-013",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-07", topic: "Medieval India",
    questionType: "long", difficulty: "hard", marks: 6, bloomLevel: "Understand",
    learningObjective: "Describe Akbar's administration.",
    source: "practice", year: null,
    question: "Describe the main features of Akbar's administration.",
    hints: ["Mansabdari; revenue; Rajputs; tolerance."],
    answer: "Mansabdari system of ranked officers; Todar Mal's revenue reforms (zabti) and jagirs; Rajput alliances and high mansabs; religious tolerance (sulh-i-kul) including abolition of jizya and pilgrimage tax; Din-i-Ilahi; Ibadat Khana discussions.",
    explanation: "Four features with one line each is ideal.",
    commonMistake: "Writing Mughal monuments instead of administration.",
  },
  {
    id: "icse-9-hc-q-his-014",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-08", topic: "The Modern Age in Europe",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Describe the impact of the Renaissance.",
    source: "practice", year: null,
    question: "Describe the impact of the Renaissance on art, literature and science.",
    hints: ["Leonardo; Shakespeare; Copernicus."],
    answer: "Art: Leonardo da Vinci (Mona Lisa), realism and perspective. Literature: Shakespeare (Hamlet, Macbeth), study of human nature. Science: Copernicus's sun-centred theory; spirit of observation and experiment.",
    explanation: "One name and one line per field.",
    commonMistake: "Naming figures without stating their contribution.",
  },
];