import type { QuestionMetadata } from "../types";

const mcqBase: Pick<QuestionMetadata, "board" | "class" | "subject" | "questionType" | "difficulty" | "marks" | "bloomLevel" | "source" | "year" | "hints"> = {
  board: "ICSE", class: 9, subject: "History & Civics",
  questionType: "mcq", difficulty: "easy", marks: 1, bloomLevel: "Remember",
  source: "practice", year: null,
  hints: ["Choose the correct option."],
};

export const mcqQuestions: QuestionMetadata[] = [
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-001", component: "Civics",
    chapterId: "icse-9-hc-civ-01", topic: "Our Constitution",
    learningObjective: "Recall the enforcement date of the Constitution.",
    question: "The Indian Constitution came into force on:",
    options: ["15 August 1947", "26 November 1949", "26 January 1950", "26 January 1949"],
    answer: "26 January 1950",
    explanation: "It was adopted on 26 November 1949 and enforced on 26 January 1950.",
    commonMistake: "Choosing 26 November 1949 (adoption).",
  },
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-002", component: "Civics",
    chapterId: "icse-9-hc-civ-01", topic: "Our Constitution",
    learningObjective: "Identify the meaning of single citizenship.",
    question: "A person has no separate citizenship of a state. This is known as:",
    options: ["Dual citizenship", "Single citizenship", "Universal franchise", "Federal citizenship"],
    answer: "Single citizenship",
    explanation: "India follows single citizenship - citizenship of India only.",
    commonMistake: "Confusing it with universal adult franchise.",
  },
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-003", component: "Civics",
    chapterId: "icse-9-hc-civ-02", topic: "Elections",
    learningObjective: "Identify the body that conducts elections.",
    question: "Elections to the Lok Sabha are conducted by:",
    options: ["The Union Cabinet", "NITI Aayog", "The Election Commission", "The Ministry of Home Affairs"],
    answer: "The Election Commission",
    explanation: "Article 324 vests the conduct of elections in the Election Commission.",
    commonMistake: "Thinking the government conducts its own elections.",
  },
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-004", component: "Civics",
    chapterId: "icse-9-hc-civ-02", topic: "Elections",
    learningObjective: "Identify a mid-term election.",
    question: "An election held when a House is dissolved before completing its normal term is called a:",
    options: ["General election", "By-election", "Mid-term election", "Presidential election"],
    answer: "Mid-term election",
    explanation: "Early dissolution of the House leads to a mid-term election.",
    commonMistake: "Confusing it with a by-election.",
  },
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-005", component: "Civics",
    chapterId: "icse-9-hc-civ-03", topic: "Local Self Government",
    learningObjective: "Identify the district-level rural body.",
    question: "Which is the district-level body of the Panchayati Raj system?",
    options: ["Gram Panchayat", "Panchayat Samiti", "Zila Parishad", "Municipal Council"],
    answer: "Zila Parishad",
    explanation: "Village - Gram Panchayat; Block - Panchayat Samiti; District - Zila Parishad.",
    commonMistake: "Mixing the levels.",
  },
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-006", component: "Civics",
    chapterId: "icse-9-hc-civ-03", topic: "Local Self Government",
    learningObjective: "Identify the head of a Municipal Corporation.",
    question: "A Municipal Corporation is headed by the:",
    options: ["Chairman", "Mayor", "Sarpanch", "District Collector"],
    answer: "Mayor",
    explanation: "Large cities: Mayor (Corporation); smaller towns: Chairman (Committee).",
    commonMistake: "Confusing Mayor with Chairman.",
  },
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-007", component: "History",
    chapterId: "icse-9-hc-his-01", topic: "The Harappan Civilisation",
    learningObjective: "Identify the Harappan dockyard site.",
    question: "The Harappan dockyard was discovered at:",
    options: ["Harappa", "Mohenjo-daro", "Lothal", "Kalibangan"],
    answer: "Lothal",
    explanation: "Lothal (Gujarat) had the dockyard, indicating maritime trade.",
    commonMistake: "Choosing Mohenjo-daro (Great Bath).",
  },
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-008", component: "History",
    chapterId: "icse-9-hc-his-01", topic: "The Harappan Civilisation",
    learningObjective: "Recall the state of the Harappan script.",
    question: "The Harappan script is:",
    options: ["Deciphered and readable", "Undeciphered", "Written in Sanskrit", "Written in Pali"],
    answer: "Undeciphered",
    explanation: "The pictographic script has not been read so far.",
    commonMistake: "Assuming it is deciphered.",
  },
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-009", component: "History",
    chapterId: "icse-9-hc-his-02", topic: "The Vedic Period",
    learningObjective: "Identify the oldest Veda.",
    question: "Which is the oldest of the four Vedas?",
    options: ["Samaveda", "Yajurveda", "Atharvaveda", "Rigveda"],
    answer: "Rigveda",
    explanation: "The Rigveda contains the earliest hymns.",
    commonMistake: "Choosing Samaveda (melodies).",
  },
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-010", component: "History",
    chapterId: "icse-9-hc-his-03", topic: "Jainism and Buddhism",
    learningObjective: "Recall Mahavira's position in Jainism.",
    question: "Mahavira is regarded as the:",
    options: ["Founder of Buddhism", "24th Tirthankara", "First Tirthankara", "Author of the Vedas"],
    answer: "24th Tirthankara",
    explanation: "He was the 24th and last Tirthankara of Jainism.",
    commonMistake: "Calling him the founder of a new religion in the strict sense.",
  },
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-011", component: "History",
    chapterId: "icse-9-hc-his-03", topic: "Jainism and Buddhism",
    learningObjective: "Recall where the Buddha preached his first sermon.",
    question: "The Buddha preached his first sermon at:",
    options: ["Bodh Gaya", "Sarnath", "Kushinagar", "Lumbini"],
    answer: "Sarnath",
    explanation: "Enlightenment at Bodh Gaya; first sermon at Sarnath; death at Kushinagar.",
    commonMistake: "Mixing up the three sites.",
  },
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-012", component: "History",
    chapterId: "icse-9-hc-his-04", topic: "The Mauryan Empire",
    learningObjective: "Identify the author of the Arthashastra.",
    question: "The Arthashastra was written by:",
    options: ["Megasthenes", "Chanakya", "Ashoka", "Harisena"],
    answer: "Chanakya",
    explanation: "Chanakya (Kautilya) wrote the Arthashastra; Megasthenes wrote Indika.",
    commonMistake: "Confusing it with Indika.",
  },
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-013", component: "History",
    chapterId: "icse-9-hc-his-04", topic: "The Mauryan Empire",
    learningObjective: "Recall the year of the Kalinga War.",
    question: "The Kalinga War was fought in:",
    options: ["322 BCE", "298 BCE", "261 BCE", "232 BCE"],
    answer: "261 BCE",
    explanation: "Ashoka's remorse after 261 BCE led to his Dhamma policy.",
    commonMistake: "Choosing 232 BCE (Ashoka's death).",
  },
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-014", component: "History",
    chapterId: "icse-9-hc-his-05", topic: "The Sangam Age",
    learningObjective: "Identify the author of the Tirukkural.",
    question: "The Tirukkural was composed by:",
    options: ["Thiruvalluvar", "Ilango Adigal", "Kambar", "Harisena"],
    answer: "Thiruvalluvar",
    explanation: "Thiruvalluvar's ethical couplets are studied in the Sangam chapter.",
    commonMistake: "Confusing with other Tamil authors.",
  },
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-015", component: "History",
    chapterId: "icse-9-hc-his-06", topic: "The Age of the Guptas",
    learningObjective: "Associate Nalanda with the Guptas.",
    question: "Nalanda University flourished mainly under the:",
    options: ["Mauryas", "Guptas", "Mughals", "Cholas"],
    answer: "Guptas",
    explanation: "Nalanda grew under Kumaragupta I as an international centre of learning.",
    commonMistake: "Attributing it to Ashoka.",
  },
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-016", component: "History",
    chapterId: "icse-9-hc-his-07", topic: "Medieval India",
    learningObjective: "Recall who completed the Qutub Minar.",
    question: "The Qutub Minar was completed by:",
    options: ["Qutb-ud-din Aibak", "Iltutmish", "Alauddin Khilji", "Akbar"],
    answer: "Iltutmish",
    explanation: "Aibak began it; Iltutmish completed it.",
    commonMistake: "Crediting the founder of the dynasty for the completion.",
  },
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-017", component: "History",
    chapterId: "icse-9-hc-his-07", topic: "Medieval India",
    learningObjective: "Associate Akbar's revenue system with its author.",
    question: "Akbar's land revenue system is associated with:",
    options: ["Todar Mal", "Abul Fazl", "Birbal", "Tansen"],
    answer: "Todar Mal",
    explanation: "Todar Mal devised the zabti (measurement-based) revenue system.",
    commonMistake: "Confusing Todar Mal with Abul Fazl (the chronicler).",
  },
  {
    ...mcqBase,
    id: "icse-9-hc-q-mcq-018", component: "History",
    chapterId: "icse-9-hc-his-08", topic: "The Modern Age in Europe",
    learningObjective: "Associate Copernicus with heliocentric theory.",
    question: "The theory that the earth moves around the sun was proposed by:",
    options: ["Leonardo da Vinci", "Copernicus", "Shakespeare", "Martin Luther"],
    answer: "Copernicus",
    explanation: "Copernicus proposed the sun-centred universe.",
    commonMistake: "Choosing Leonardo da Vinci.",
  },
];