export const quickRevision = {
  grammar: {
    partsOfSpeech: "Eight categories; function decides category.",
    tenses: "3 times × 4 aspects = 12 tenses.",
    subjectVerbAgreement: "Verb agrees with true subject, not intervening phrase.",
    articles: "a/an = sound-based; the = specific/unique/superlative.",
    prepositions: "at=point, on=surface/day, in=enclosed/month/year.",
    conjunctions: "FANBOYS = coordinating; never although+but.",
    pronouns: "Subject vs object position matters.",
    adjectives: "OSASCOMP order; comparative for two, superlative for 3+.",
    adverbs: "Modify verbs/adjectives/adverbs; hard vs hardly.",
    activePassiveVoice: "be + V3; preserve tense.",
    directIndirectSpeech: "Pronouns, tense, time/place change.",
    transformation: "Same meaning, different form.",
    questionTags: "Same auxiliary, opposite polarity.",
    punctuation: "its vs it's; comma splice error.",
    clauses: "Independent vs dependent; noun/adj/adv types.",
    phrases: "No subject-verb; functions: noun/verb/adj/adv.",
    sentenceStructure: "Simple=1, Compound=2+, Complex=ind+dep.",
  },
  composition: {
    fundamentals: "PAM: Purpose, Audience, Mode.",
    descriptive: "Show, don't tell; all five senses.",
    narrative: "Arc: Exposition → Rising → Climax → Falling → Resolution.",
    argumentative: "PEE: Point, Evidence, Explanation.",
    storyWriting: "Integrate given line/title; one conflict.",
    pictureComposition: "Picture is prompt; 3-4 elements.",
    letterWriting: "Format + tone + purpose.",
    noticeEmail: "5 W's; subject line.",
  },
  literature: {
    prose: ["Bonku Babu: self-respect.", "Oliver: injustice.", "Millionaire: irony.", "Home-coming: neglect.", "Bank: rumours."],
    poetry: ["Night Mail: rhythm.", "Skimbleshanks: anthropomorphism.", "I Remember: nostalgia.", "Doctor's Journal: horror + compassion.", "Artifice: bonsai = women."],
    drama: ["Julius Caesar: tragic hero, manipulation, fate vs free will."],
  },
};
