import type { QuestionMetadata } from "../types";

export const civicsMockTest1: QuestionMetadata[] = [
  {
    id: "icse-10-hc-test-civ-001",
    board: "ICSE", class: 10, subject: "History & Civics", component: "Civics",
    chapterId: "icse-10-hc-civ-01", topic: "The Union Legislature",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall Speaker removal procedure.",
    source: "board-style", year: null,
    question: "How can the Speaker of the Lok Sabha be removed?",
    hints: ["Notice; majority."],
    answer: "By a resolution of the House passed by a majority of all its then members, after at least 14 days' notice.",
    explanation: "Notice + majority.",
    commonMistake: "Omitting the notice period.",
  },
  {
    id: "icse-10-hc-test-civ-002",
    board: "ICSE", class: 10, subject: "History & Civics", component: "Civics",
    chapterId: "icse-10-hc-civ-01", topic: "The Union Legislature",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Explain parliamentary control of the executive.",
    source: "board-style", year: null,
    question: "How does Parliament control the executive? State any four ways.",
    hints: ["Questions; motions."],
    answer: "Question hour; adjournment motions; no-confidence motion; debates and committees (any four).",
    explanation: "Name the instruments of control.",
    commonMistake: "Listing powers not related to control.",
  },
  {
    id: "icse-10-hc-test-civ-003",
    board: "ICSE", class: 10, subject: "History & Civics", component: "Civics",
    chapterId: "icse-10-hc-civ-02", topic: "The Union Executive",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Explain President's emergency powers.",
    source: "board-style", year: null,
    question: "Describe the three types of emergency and any two effects of the National Emergency.",
    hints: ["352, 356, 360."],
    answer: "National (352), State (356), Financial (360). Effects of National Emergency: Fundamental Rights may be curbed; the Union can direct state governments.",
    explanation: "Three types + two effects.",
    commonMistake: "Swapping effects between emergencies.",
  },
  {
    id: "icse-10-hc-test-civ-004",
    board: "ICSE", class: 10, subject: "History & Civics", component: "Civics",
    chapterId: "icse-10-hc-civ-03", topic: "The Judiciary",
    questionType: "short", difficulty: "medium", marks: 3, bloomLevel: "Remember",
    learningObjective: "Recall High Court facts.",
    source: "board-style", year: null,
    question: "State two qualifications for appointment as a High Court judge and the retirement age.",
    hints: ["10 years; 62."],
    answer: "Citizen of India with 10 years' judicial office or 10 years as High Court advocate; retirement at 62.",
    explanation: "Qualification + age.",
    commonMistake: "Using the Supreme Court's 65.",
  },
  {
    id: "icse-10-hc-test-civ-005",
    board: "ICSE", class: 10, subject: "History & Civics", component: "Civics",
    chapterId: "icse-10-hc-civ-03", topic: "The Judiciary",
    questionType: "long", difficulty: "hard", marks: 6, bloomLevel: "Analyse",
    learningObjective: "Evaluate judicial protection of rights.",
    source: "board-style", year: null,
    question: "How does the judiciary protect the Fundamental Rights of citizens? Illustrate with writs.",
    hints: ["Writs; review."],
    answer: "Through writ jurisdiction (habeas corpus, mandamus, prohibition, certiorari, quo warranto) and judicial review; courts can strike down unconstitutional laws and order authorities to act or refrain.",
    explanation: "Mechanisms + examples.",
    commonMistake: "Discussing only structure, not protection.",
  },
];

export const historyMockTest1: QuestionMetadata[] = [
  {
    id: "icse-10-hc-test-his-001",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-01", topic: "The Indian National Movement (1857-1917)",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Describe the Revolt's causes.",
    source: "board-style", year: null,
    question: "Describe any four causes of the Revolt of 1857.",
    hints: ["Four categories."],
    answer: "Political (Doctrine of Lapse, annexations); socio-religious (conversion fears, racial arrogance); economic (revenue, drain); military (discrimination, cartridges) - any four with one line each.",
    explanation: "Balance across categories.",
    commonMistake: "Military-only answers.",
  },
  {
    id: "icse-10-hc-test-his-002",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-01", topic: "The Indian National Movement (1857-1917)",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Explain the growth of nationalism.",
    source: "board-style", year: null,
    question: "Explain any four factors that led to the growth of nationalism in India.",
    hints: ["Exploitation; reformers; press."],
    answer: "Economic exploitation; repressive colonial policies; socio-religious reform movements; role of the press (any four, with details).",
    explanation: "Four factors with a line each.",
    commonMistake: "Vague points without examples.",
  },
  {
    id: "icse-10-hc-test-his-003",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-02", topic: "Mass Phase of the National Movement (1915-1947)",
    questionType: "structured", difficulty: "hard", marks: 4, bloomLevel: "Analyse",
    learningObjective: "Explain CDM events.",
    source: "board-style", year: null,
    question: "Describe the course of the Civil Disobedience Movement from the Dandi March to its renewal.",
    hints: ["Dandi; Pact; 2nd RTC."],
    answer: "Dandi March (1930) and salt law breaking; mass participation; Gandhi-Irwin Pact (1931); Second Round Table Conference failure; renewal in 1932 with repression.",
    explanation: "Chronological chain is essential.",
    commonMistake: "Stopping before the renewal.",
  },
  {
    id: "icse-10-hc-test-his-004",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-02", topic: "Mass Phase of the National Movement (1915-1947)",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall the QIM resolution date.",
    source: "board-style", year: null,
    question: "When was the Quit India Resolution passed and with what message?",
    hints: ["8 August 1942."],
    answer: "8 August 1942, with the message 'Do or Die' for ending British rule.",
    explanation: "Date + slogan.",
    commonMistake: "Confusing with the NCM's suspension.",
  },
  {
    id: "icse-10-hc-test-his-005",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-03", topic: "The Contemporary World",
    questionType: "long", difficulty: "hard", marks: 6, bloomLevel: "Evaluate",
    learningObjective: "Assess WWII's consequences.",
    source: "board-style", year: null,
    question: "Describe the consequences of the Second World War, including the formation of the UN and the Cold War.",
    hints: ["Axis defeat; UN; Cold War."],
    answer: "Defeat of Axis powers (1945); formation of the UN to keep peace; start of the Cold War (meaning, NATO 1949, Warsaw Pact 1955); end of the old imperial order.",
    explanation: "Consequences with the three named items.",
    commonMistake: "Narrating causes instead.",
  },
];

export const mixedMockTest1: QuestionMetadata[] = [
  {
    id: "icse-10-hc-test-mix-001",
    board: "ICSE", class: 10, subject: "History & Civics", component: "Civics",
    chapterId: "icse-10-hc-civ-01", topic: "The Union Legislature",
    questionType: "short", difficulty: "medium", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall quorum.",
    source: "board-style", year: null,
    question: "What is quorum in Parliament? State the requirement.",
    hints: ["One-tenth."],
    answer: "The minimum attendance required for a valid sitting - one-tenth of the total membership.",
    explanation: "Definition + figure.",
    commonMistake: "Stating a different fraction.",
  },
  {
    id: "icse-10-hc-test-mix-002",
    board: "ICSE", class: 10, subject: "History & Civics", component: "Civics",
    chapterId: "icse-10-hc-civ-02", topic: "The Union Executive",
    questionType: "short", difficulty: "medium", marks: 2, bloomLevel: "Understand",
    learningObjective: "Explain collective responsibility.",
    source: "board-style", year: null,
    question: "What is collective responsibility of the Council of Ministers?",
    hints: ["Lok Sabha confidence."],
    answer: "The whole Council is jointly responsible to the Lok Sabha; a vote of no confidence against one policy brings down the entire ministry.",
    explanation: "Body + consequence.",
    commonMistake: "Confusing with individual responsibility.",
  },
  {
    id: "icse-10-hc-test-mix-003",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-01", topic: "The Indian National Movement (1857-1917)",
    questionType: "short", difficulty: "medium", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall Swadeshi movement.",
    source: "board-style", year: null,
    question: "Why did the Swadeshi and Boycott movement begin in 1905?",
    hints: ["Partition of Bengal."],
    answer: "To protest against Lord Curzon's Partition of Bengal (1905); people boycotted British goods and used Indian products.",
    explanation: "Trigger + method.",
    commonMistake: "Unrelated triggers.",
  },
  {
    id: "icse-10-hc-test-mix-004",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-02", topic: "Mass Phase of the National Movement (1915-1947)",
    questionType: "structured", difficulty: "hard", marks: 4, bloomLevel: "Understand",
    learningObjective: "Explain the Map of independence.",
    source: "board-style", year: null,
    question: "What were the main clauses of the Indian Independence Act, 1947?",
    hints: ["Two dominions."],
    answer: "Created two independent dominions (India and Pakistan); constituent assemblies became sovereign; British paramountcy over princely states ended; provisions for boundaries.",
    explanation: "Clause-based answer.",
    commonMistake: "Mixing Mountbatten Plan clauses.",
  },
  {
    id: "icse-10-hc-test-mix-005",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-03", topic: "The Contemporary World",
    questionType: "short", difficulty: "medium", marks: 3, bloomLevel: "Remember",
    learningObjective: "Recall NAM facts.",
    source: "board-style", year: null,
    question: "What is Panchsheel? Who were the architects of NAM?",
    hints: ["1954; five leaders."],
    answer: "Panchsheel (1954): the Five Principles of Peaceful Coexistence. Architects: Nehru, Nasser, Tito, Sukarno, Nkrumah.",
    explanation: "Meaning + names.",
    commonMistake: "Missing two of the five names.",
  },
  {
    id: "icse-10-hc-test-mix-006",
    board: "ICSE", class: 10, subject: "History & Civics", component: "Civics",
    chapterId: "icse-10-hc-civ-03", topic: "The Judiciary",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Explain subordinate courts.",
    source: "board-style", year: null,
    question: "Distinguish between the Court of the District Judge and the Sessions Court, and explain Lok Adalats.",
    hints: ["Civil vs criminal."],
    answer: "District Judge court tries civil cases; Sessions Court tries serious criminal cases; the same officer may preside over both. Lok Adalats settle disputes by compromise quickly and without court fees.",
    explanation: "Distinction + Lok Adalat meaning.",
    commonMistake: "Reversing civil and criminal.",
  },
];

export const mockTests: QuestionMetadata[][] = [civicsMockTest1, historyMockTest1, mixedMockTest1];