import type { QuestionMetadata } from "../types";

export const civicsMockTest1: QuestionMetadata[] = [
  {
    id: "icse-9-hc-test-civ-001",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-01", topic: "Our Constitution",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall key constitutional facts.",
    source: "board-style", year: null,
    question: "State the date of adoption and the date of enforcement of the Indian Constitution.",
    hints: ["Two dates."],
    answer: "Adopted 26 November 1949; enforced 26 January 1950.",
    explanation: "Partial I style short answer.",
    commonMistake: "Reversing the dates.",
  },
  {
    id: "icse-9-hc-test-civ-002",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-01", topic: "Our Constitution",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Explain salient features.",
    source: "board-style", year: null,
    question: "Explain any four salient features of the Indian Constitution.",
    hints: ["Single citizenship, FR, UAF, DPSP, welfare state."],
    answer: "Single citizenship; Fundamental Rights and Duties (names); universal adult franchise; Directive Principles of State Policy; welfare state (any four with one line each).",
    explanation: "Four features with a line each.",
    commonMistake: "Writing features without explanation.",
  },
  {
    id: "icse-9-hc-test-civ-003",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-02", topic: "Elections",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall the composition of the Election Commission.",
    source: "board-style", year: null,
    question: "State the composition of the Election Commission of India.",
    hints: ["One + two."],
    answer: "Chief Election Commissioner and two other Election Commissioners.",
    explanation: "Direct factual recall.",
    commonMistake: "Forgetting the other two commissioners.",
  },
  {
    id: "icse-9-hc-test-civ-004",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-02", topic: "Elections",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Distinguish types of election.",
    source: "board-style", year: null,
    question: "Distinguish between a general election and a by-election. When is a mid-term election held?",
    hints: ["Whole House vs single seat."],
    answer: "General election: all/most seats filled on completion of term; by-election: single casual vacancy; mid-term election: when a House is dissolved before its term ends.",
    explanation: "Definitions plus the mid-term condition.",
    commonMistake: "Confusing by-election with mid-term.",
  },
  {
    id: "icse-9-hc-test-civ-005",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-03", topic: "Local Self Government",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Explain Panchayati Raj.",
    source: "board-style", year: null,
    question: "Explain the three-tier structure of the Panchayati Raj system.",
    hints: ["Village-block-district."],
    answer: "Gram Panchayat at village level; Panchayat Samiti at block level; Zila Parishad at district level - with one function of each.",
    explanation: "Three tiers in order.",
    commonMistake: "Missing functions.",
  },
  {
    id: "icse-9-hc-test-civ-006",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-03", topic: "Local Self Government",
    questionType: "long", difficulty: "medium", marks: 6, bloomLevel: "Analyse",
    learningObjective: "Evaluate the importance of local self-government.",
    source: "board-style", year: null,
    question: "Why is local self-government important in a democracy? Illustrate with examples of rural and urban bodies.",
    hints: ["Participation; quick solutions; training."],
    answer: "It ensures participation, solves local problems quickly and trains citizens in democracy; e.g. Gram Panchayats handle water and sanitation; Municipal Corporations manage city services like roads, water and fire services.",
    explanation: "Reasons + concrete examples.",
    commonMistake: "Only listing bodies without reasons.",
  },
];

export const historyMockTest1: QuestionMetadata[] = [
  {
    id: "icse-9-hc-test-his-001",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-01", topic: "The Harappan Civilisation",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Describe Harappan urban planning.",
    source: "board-style", year: null,
    question: "Describe any four features of the town planning of the Harappan Civilisation.",
    hints: ["Citadel; grid; bricks; drains."],
    answer: "Citadel-Lower Town division; grid streets; standardised burnt bricks; covered drains; public buildings like the Great Bath (any four).",
    explanation: "Four features, one line each.",
    commonMistake: "Writing trade features instead of planning.",
  },
  {
    id: "icse-9-hc-test-his-002",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-02", topic: "The Vedic Period",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Analyse",
    learningObjective: "Compare Vedic phases.",
    source: "board-style", year: null,
    question: "Mention any four differences between Early Vedic and Later Vedic society.",
    hints: ["Polity, economy, society, women."],
    answer: "Polity: tribal Raja + active assemblies vs. powerful kings + weakened assemblies. Economy: pastoral vs. agricultural. Society: flexible vs. rigid varna. Women: participation and education vs. declining status (any four paired differences).",
    explanation: "Paired points are essential.",
    commonMistake: "Unpaired description.",
  },
  {
    id: "icse-9-hc-test-his-003",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-03", topic: "Jainism and Buddhism",
    questionType: "short", difficulty: "easy", marks: 3, bloomLevel: "Remember",
    learningObjective: "Recall Jain doctrines.",
    source: "board-style", year: null,
    question: "Name the five vows of Jainism and state which is the most important.",
    hints: ["Ahimsa."],
    answer: "Ahimsa, satya, asteya, aparigraha, brahmacharya; ahimsa (non-violence) is the most important.",
    explanation: "List + highlight ahimsa.",
    commonMistake: "Missing that ahimsa is central.",
  },
  {
    id: "icse-9-hc-test-his-004",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-04", topic: "The Mauryan Empire",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Describe sources of Mauryan history.",
    source: "board-style", year: null,
    question: "Name and explain any two sources of Mauryan history.",
    hints: ["Text + inscription."],
    answer: "Any two: Arthashastra (Chanakya's statecraft), Indika (Megasthenes' account), Ashokan edicts (royal messages), Sanchi Stupa (monument).",
    explanation: "Name each source and say what it tells us.",
    commonMistake: "Only naming without explaining.",
  },
  {
    id: "icse-9-hc-test-his-005",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-06", topic: "The Age of the Guptas",
    questionType: "short", difficulty: "easy", marks: 3, bloomLevel: "Remember",
    learningObjective: "Recall Gupta achievements.",
    source: "board-style", year: null,
    question: "Mention any three achievements of the Gupta period.",
    hints: ["Nalanda; Kalidasa; Aryabhatta."],
    answer: "Any three: Nalanda University; Kalidasa's literature; Deogarh temple; Aryabhatta's science.",
    explanation: "One line each.",
    commonMistake: "Vague answers without names.",
  },
  {
    id: "icse-9-hc-test-his-006",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-07", topic: "Medieval India",
    questionType: "long", difficulty: "hard", marks: 6, bloomLevel: "Analyse",
    learningObjective: "Analyse Tughlaq's experiments.",
    source: "board-style", year: null,
    question: "Describe the main experiments of Muhammad Bin Tughlaq and explain why they failed.",
    hints: ["Capital; token currency; taxes."],
    answer: "Capital shifted to Daulatabad (difficult to manage, north unsettled); token currency (forgeries, loss of confidence); heavy Doab taxation during famine. Reforms without preparation failed and weakened the Sultanate.",
    explanation: "Each experiment + reason for failure.",
    commonMistake: "Listing experiments without reasons.",
  },
];

export const mixedMockTest1: QuestionMetadata[] = [
  {
    id: "icse-9-hc-test-mix-001",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-02", topic: "Elections",
    questionType: "very-short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall election concepts.",
    source: "board-style", year: null,
    question: "What is meant by a by-election?",
    hints: ["Single vacancy."],
    answer: "An election held to fill a casual vacancy in a single constituency.",
    explanation: "Definition with keyword 'casual vacancy'.",
    commonMistake: "Confusing with mid-term.",
  },
  {
    id: "icse-9-hc-test-mix-002",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-03", topic: "Jainism and Buddhism",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Explain the Eightfold Path.",
    source: "board-style", year: null,
    question: "Explain the Eightfold Path of Buddhism.",
    hints: ["Eight steps; conduct + meditation."],
    answer: "Right view, resolve, speech, action, livelihood, effort, mindfulness, concentration - a course of right living and meditation leading to the end of suffering (nirvana).",
    explanation: "Name the steps and state the goal.",
    commonMistake: "Naming fewer than eight steps.",
  },
  {
    id: "icse-9-hc-test-mix-003",
    board: "ICSE", class: 9, subject: "History & Civics", component: "Civics",
    chapterId: "icse-9-hc-civ-01", topic: "Our Constitution",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Explain welfare-related principles.",
    source: "board-style", year: null,
    question: "Explain the meaning of the welfare state and the role of the Directive Principles.",
    hints: ["Well-being; guidelines."],
    answer: "A welfare state takes responsibility for citizens' well-being; the Directive Principles guide governments towards social and economic welfare (equality, livelihood, education, health).",
    explanation: "Definition + link.",
    commonMistake: "Writing the Preamble instead.",
  },
  {
    id: "icse-9-hc-test-mix-004",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-01", topic: "The Harappan Civilisation",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall sources.",
    source: "board-style", year: null,
    question: "Name the site of the Great Bath and one thing it suggests about Harappan life.",
    hints: ["Mohenjo-daro."],
    answer: "Mohenjo-daro; it suggests the importance of ritual bathing and public architecture.",
    explanation: "Site + inference.",
    commonMistake: "Naming Lothal.",
  },
  {
    id: "icse-9-hc-test-mix-005",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-08", topic: "The Modern Age in Europe",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Explain the Reformation.",
    source: "board-style", year: null,
    question: "What was the Reformation? State two of its results.",
    hints: ["Church reform; Protestantism."],
    answer: "A 16th-century movement to reform the Catholic Church led by Martin Luther (1517); results: division into Catholic and Protestant churches; spread of Bible translations and literacy.",
    explanation: "Definition + two results.",
    commonMistake: "Calling it a political war.",
  },
  {
    id: "icse-9-hc-test-mix-006",
    board: "ICSE", class: 9, subject: "History & Civics", component: "History",
    chapterId: "icse-9-hc-his-05", topic: "The Sangam Age",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall Sangam facts.",
    source: "board-style", year: null,
    question: "Name the three Tamil kingdoms of the Sangam age.",
    hints: ["Three C's."],
    answer: "The Cheras, the Cholas and the Pandyas.",
    explanation: "Direct recall.",
    commonMistake: "Spelling errors.",
  },
];

export const mockTests: QuestionMetadata[][] = [civicsMockTest1, historyMockTest1, mixedMockTest1];