import type { QuestionMetadata } from "../types";

export const civicsQuestions: QuestionMetadata[] = [
  {
    id: "icse-10-hc-q-civ-001",
    board: "ICSE", class: 10, subject: "History & Civics", component: "Civics",
    chapterId: "icse-10-hc-civ-01", topic: "The Union Legislature",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall the composition of Parliament.",
    source: "practice", year: null,
    question: "What is the composition of the Union Parliament?",
    hints: ["Three parts."],
    answer: "The President, the Lok Sabha and the Rajya Sabha.",
    explanation: "Parliament is not just the two Houses.",
    commonMistake: "Omitting the President.",
  },
  {
    id: "icse-10-hc-q-civ-002",
    board: "ICSE", class: 10, subject: "History & Civics", component: "Civics",
    chapterId: "icse-10-hc-civ-01", topic: "The Union Legislature",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Explain the exclusive powers of each House.",
    source: "practice", year: null,
    question: "Explain the exclusive powers of the Lok Sabha and the Rajya Sabha.",
    hints: ["Money bills; Article 249/312."],
    answer: "Lok Sabha: money bills and the no-confidence motion. Rajya Sabha: authorise laws on State List subjects in the national interest (Art 249) and create All India Services (Art 312).",
    explanation: "Two powers each with article references.",
    commonMistake: "Giving shared powers as exclusive.",
  },
  {
    id: "icse-10-hc-q-civ-003",
    board: "ICSE", class: 10, subject: "History & Civics", component: "Civics",
    chapterId: "icse-10-hc-civ-01", topic: "The Union Legislature",
    questionType: "analytical", difficulty: "hard", marks: 4, bloomLevel: "Analyse",
    learningObjective: "Compare types of questions in Parliament.",
    source: "practice", year: null,
    question: "Distinguish between starred, unstarred and short-notice questions.",
    hints: ["Notice; oral vs written."],
    answer: "Starred: 10 days' notice, answered orally, supplementary questions allowed. Unstarred: written answer, no supplementaries. Short notice: less than 10 days, oral if admitted.",
    explanation: "Notice period + manner of answer.",
    commonMistake: "Swapping oral and written.",
  },
  {
    id: "icse-10-hc-q-civ-004",
    board: "ICSE", class: 10, subject: "History & Civics", component: "Civics",
    chapterId: "icse-10-hc-civ-02", topic: "The Union Executive",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall the President's qualifications.",
    source: "practice", year: null,
    question: "State any two qualifications for the office of the President of India.",
    hints: ["35; citizen."],
    answer: "Must be a citizen of India; must be at least 35 years old (also: qualified for Lok Sabha membership).",
    explanation: "Two conditions suffice for two marks.",
    commonMistake: "Confusing age with the Vice-President's.",
  },
  {
    id: "icse-10-hc-q-civ-005",
    board: "ICSE", class: 10, subject: "History & Civics", component: "Civics",
    chapterId: "icse-10-hc-civ-02", topic: "The Union Executive",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Explain impeachment.",
    source: "practice", year: null,
    question: "Describe the procedure for impeachment of the President.",
    hints: ["Violation; notice; majority."],
    answer: "Ground: violation of the Constitution. A House frames charges with 14 days' notice; the resolution must be passed by a two-thirds majority of the total membership of both Houses.",
    explanation: "Ground + notice + double special majority.",
    commonMistake: "Forgetting the majority applies to total membership.",
  },
  {
    id: "icse-10-hc-q-civ-006",
    board: "ICSE", class: 10, subject: "History & Civics", component: "Civics",
    chapterId: "icse-10-hc-civ-02", topic: "The Union Executive",
    questionType: "analytical", difficulty: "medium", marks: 4, bloomLevel: "Analyse",
    learningObjective: "Distinguish CoM and Cabinet.",
    source: "practice", year: null,
    question: "Distinguish between the Council of Ministers and the Cabinet.",
    hints: ["Size; function."],
    answer: "The Council of Ministers comprises all ministers of all ranks; the Cabinet is the smaller core of senior ministers that decides major policy.",
    explanation: "Two contrasts: composition and power.",
    commonMistake: "Thinking they are the same body.",
  },
  {
    id: "icse-10-hc-q-civ-007",
    board: "ICSE", class: 10, subject: "History & Civics", component: "Civics",
    chapterId: "icse-10-hc-civ-03", topic: "The Judiciary",
    questionType: "short", difficulty: "medium", marks: 3, bloomLevel: "Remember",
    learningObjective: "Name the writs.",
    source: "practice", year: null,
    question: "Name any three writs issued by the courts and state what one of them does.",
    hints: ["Habeas corpus first."],
    answer: "Any three of: habeas corpus, mandamus, prohibition, certiorari, quo warranto. Habeas corpus orders the production of a detained person to check the legality of detention.",
    explanation: "Three names + one-line function of one.",
    commonMistake: "Spelling errors in writ names.",
  },
  {
    id: "icse-10-hc-q-civ-008",
    board: "ICSE", class: 10, subject: "History & Civics", component: "Civics",
    chapterId: "icse-10-hc-civ-03", topic: "The Judiciary",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Explain judicial review and court of record.",
    source: "practice", year: null,
    question: "Explain judicial review and the Supreme Court as a Court of Record.",
    hints: ["Unconstitutional; contempt."],
    answer: "Judicial review: the power to declare laws/actions unconstitutional. Court of record: proceedings are permanent evidence and the court can punish for contempt.",
    explanation: "Two definitions with functions.",
    commonMistake: "Mixing judicial review with appellate jurisdiction.",
  },
  {
    id: "icse-10-hc-q-civ-009",
    board: "ICSE", class: 10, subject: "History & Civics", component: "Civics",
    chapterId: "icse-10-hc-civ-03", topic: "The Judiciary",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall Lok Adalat features.",
    source: "practice", year: null,
    question: "What are Lok Adalats? State one advantage.",
    hints: ["People's court."],
    answer: "People's courts that settle disputes by compromise; advantages: no court fee, quick justice (any one).",
    explanation: "Meaning + one advantage.",
    commonMistake: "Describing them as regular courts.",
  },
];