import type { QuestionMetadata } from "../types";

export const historyQuestions: QuestionMetadata[] = [
  {
    id: "icse-10-hc-q-his-001",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-01", topic: "The Indian National Movement (1857-1917)",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Describe consequences of 1857.",
    source: "practice", year: null,
    question: "Describe any four consequences of the First War of Independence, 1857.",
    hints: ["Administration; Proclamation; states; army."],
    answer: "Crown rule replaced Company rule; Queen Victoria's Proclamation (1858); princely states assured no annexation; army reorganised (more British soldiers, artillery with British).",
    explanation: "The four syllabus areas - one line each.",
    commonMistake: "Narrating battles instead of consequences.",
  },
  {
    id: "icse-10-hc-q-his-002",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-01", topic: "The Indian National Movement (1857-1917)",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall INC foundation facts.",
    source: "practice", year: null,
    question: "Who founded the Indian National Congress and when? Name its first President.",
    hints: ["1885; Hume."],
    answer: "A.O. Hume founded it in 1885; the first President was W.C. Bonnerjee (Bombay session).",
    explanation: "Founder + year + first President.",
    commonMistake: "Calling Dadabhai Naoroji the first President.",
  },
  {
    id: "icse-10-hc-q-his-003",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-01", topic: "The Indian National Movement (1857-1917)",
    questionType: "analytical", difficulty: "hard", marks: 4, bloomLevel: "Analyse",
    learningObjective: "Compare phases of the Congress.",
    source: "practice", year: null,
    question: "Distinguish between the Early Nationalists and the Assertive Nationalists in objectives and methods.",
    hints: ["Reform vs swaraj; petitions vs boycott."],
    answer: "Early Nationalists: sought reform within the system through constitutional methods (petitions, meetings). Assertive Nationalists: demanded swaraj, using boycott, passive resistance and national education.",
    explanation: "Objectives + methods, both sides.",
    commonMistake: "One-sided comparisons.",
  },
  {
    id: "icse-10-hc-q-his-004",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-01", topic: "The Indian National Movement (1857-1917)",
    questionType: "short", difficulty: "medium", marks: 3, bloomLevel: "Understand",
    learningObjective: "Explain the Lucknow Pact.",
    source: "practice", year: null,
    question: "What was the Lucknow Pact (1916)? State one of its impacts.",
    hints: ["Congress-League unity."],
    answer: "An agreement between the Congress and the Muslim League (1916) on joint political demands; impact: Hindu-Muslim cooperation and united pressure for self-government.",
    explanation: "Nature + impact.",
    commonMistake: "Confusing it with the Surat Split.",
  },
  {
    id: "icse-10-hc-q-his-005",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-02", topic: "Mass Phase of the National Movement (1915-1947)",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Explain NCM causes and programme.",
    source: "practice", year: null,
    question: "Why did Gandhi launch the Non-Cooperation Movement? Describe its programme.",
    hints: ["Rowlatt; Jallianwala; Khilafat."],
    answer: "Causes: Rowlatt Act, Jallianwala Bagh, Khilafat issue. Programme: surrender of titles; boycott of government institutions, courts and foreign goods; khadi; Hindu-Muslim unity.",
    explanation: "Causes + programme structure.",
    commonMistake: "Omitting the Khilafat cause.",
  },
  {
    id: "icse-10-hc-q-his-006",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-02", topic: "Mass Phase of the National Movement (1915-1947)",
    questionType: "short", difficulty: "medium", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall CDM causes.",
    source: "practice", year: null,
    question: "State the two causes of the Civil Disobedience Movement.",
    hints: ["Simon; Poorna Swaraj."],
    answer: "Reaction to the all-British Simon Commission and the declaration of Poorna Swaraj at Lahore (1929).",
    explanation: "Syllabus-listed causes.",
    commonMistake: "Adding unrelated causes from other movements.",
  },
  {
    id: "icse-10-hc-q-his-007",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-02", topic: "Mass Phase of the National Movement (1915-1947)",
    questionType: "structured", difficulty: "hard", marks: 4, bloomLevel: "Analyse",
    learningObjective: "Assess Quit India significance.",
    source: "practice", year: null,
    question: "Describe the Quit India Movement and explain its significance.",
    hints: ["8 August 1942; Do or Die."],
    answer: "Launched 8 August 1942 ('Do or Die') after the Cripps Mission's failure and the Japanese threat; leaders jailed; mass strikes and underground activity; significance: proved British rule could not continue without Indian consent.",
    explanation: "Event + significance.",
    commonMistake: "Describing only causes.",
  },
  {
    id: "icse-10-hc-q-his-008",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-02", topic: "Mass Phase of the National Movement (1915-1947)",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall Bose's contributions.",
    source: "practice", year: null,
    question: "Mention two contributions of Subhas Chandra Bose to the freedom struggle.",
    hints: ["Forward Bloc; INA."],
    answer: "Formed the Forward Bloc (1939); reorganized and led the INA; headed the Free India Government at Singapore (any two).",
    explanation: "Two distinct contributions.",
    commonMistake: "Vague references without the names of his organisations.",
  },
  {
    id: "icse-10-hc-q-his-009",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-02", topic: "Mass Phase of the National Movement (1915-1947)",
    questionType: "structured", difficulty: "hard", marks: 4, bloomLevel: "Understand",
    learningObjective: "Explain the Cabinet Mission and Mountbatten Plan.",
    source: "practice", year: null,
    question: "State any four clauses of the Mountbatten Plan.",
    hints: ["Partition; boundaries; plebiscites; states."],
    answer: "Partition accepted in principle into two states; boundary commissions for Punjab and Bengal; plebiscites in NWFP and Sylhet; princely states free to accede to either dominion.",
    explanation: "Four clauses from the plan.",
    commonMistake: "Mixing Cabinet Mission clauses into the answer.",
  },
  {
    id: "icse-10-hc-q-his-010",
    board: "ICSE", class: 10, subject: "History & Civics", component: "History",
    chapterId: "icse-10-hc-his-03", topic: "The Contemporary World",
    questionType: "structured", difficulty: "medium", marks: 4, bloomLevel: "Understand",
    learningObjective: "Explain UN organs.",
    source: "practice", year: null,
    question: "Describe the composition and one function each of the General Assembly and the Security Council.",
    hints: ["All members; 15."],
    answer: "General Assembly: all member states, one vote each; discusses and recommends on world issues. Security Council: 15 members (5 permanent with veto + 10 elected); primary responsibility for peace and security.",
    explanation: "Composition + function for both.",
    commonMistake: "Forgetting the veto.",
  },
];