import type { QuestionMetadata } from "../types";

const mcqBase: Pick<QuestionMetadata, "board" | "class" | "subject" | "questionType" | "difficulty" | "marks" | "bloomLevel" | "source" | "year" | "hints"> = {
  board: "ICSE", class: 10, subject: "History & Civics",
  questionType: "mcq", difficulty: "easy", marks: 1, bloomLevel: "Remember",
  source: "practice", year: null,
  hints: ["Choose the correct option."],
};

export const mcqQuestions: QuestionMetadata[] = [
  {
    ...mcqBase,
    id: "icse-10-hc-q-mcq-001", component: "Civics",
    chapterId: "icse-10-hc-civ-01", topic: "The Union Legislature",
    learningObjective: "Recall the maximum strength of the Lok Sabha.",
    question: "The maximum strength of the Lok Sabha is:",
    options: ["500", "545 only", "550", "552"],
    answer: "550",
    explanation: "530 from States + 20 from Union Territories.",
    commonMistake: "Using outdated figures of 552.",
  },
  {
    ...mcqBase,
    id: "icse-10-hc-q-mcq-002", component: "Civics",
    chapterId: "icse-10-hc-civ-01", topic: "The Union Legislature",
    learningObjective: "Identify the House that alone passes money bills.",
    question: "Money bills can be introduced only in the:",
    options: ["Rajya Sabha", "Lok Sabha", "Either House", "Joint sitting"],
    answer: "Lok Sabha",
    explanation: "With the President's recommendation; the Rajya Sabha may only retain for 14 days.",
    commonMistake: "Thinking the Rajya Sabha can amend money bills.",
  },
  {
    ...mcqBase,
    id: "icse-10-hc-q-mcq-003", component: "Civics",
    chapterId: "icse-10-hc-civ-01", topic: "The Union Legislature",
    learningObjective: "Recall the tenure of Rajya Sabha members.",
    question: "Members of the Rajya Sabha serve for:",
    options: ["5 years", "4 years", "6 years", "Life"],
    answer: "6 years",
    explanation: "One-third retires every two years; the House is never dissolved.",
    commonMistake: "Confusing with the 5-year Lok Sabha term.",
  },
  {
    ...mcqBase,
    id: "icse-10-hc-q-mcq-004", component: "Civics",
    chapterId: "icse-10-hc-civ-02", topic: "The Union Executive",
    learningObjective: "Recall the minimum age for the President.",
    question: "The minimum age for election as President of India is:",
    options: ["25 years", "30 years", "35 years", "40 years"],
    answer: "35 years",
    explanation: "Citizen of India; 35+; qualified for Lok Sabha.",
    commonMistake: "Confusing with 30 (VP) or 25 (LS).",
  },
  {
    ...mcqBase,
    id: "icse-10-hc-q-mcq-005", component: "Civics",
    chapterId: "icse-10-hc-civ-02", topic: "The Union Executive",
    learningObjective: "Identify the National Emergency article.",
    question: "National Emergency is proclaimed under Article:",
    options: ["352", "356", "360", "143"],
    answer: "352",
    explanation: "352 National; 356 State (President's rule); 360 Financial.",
    commonMistake: "Swapping the three articles.",
  },
  {
    ...mcqBase,
    id: "icse-10-hc-q-mcq-006", component: "Civics",
    chapterId: "icse-10-hc-civ-03", topic: "The Judiciary",
    learningObjective: "Recall Supreme Court retirement age.",
    question: "Judges of the Supreme Court retire at the age of:",
    options: ["60", "62", "65", "68"],
    answer: "65",
    explanation: "Supreme Court 65; High Court 62.",
    commonMistake: "Confusing with the High Court's 62.",
  },
  {
    ...mcqBase,
    id: "icse-10-hc-q-mcq-007", component: "Civics",
    chapterId: "icse-10-hc-civ-03", topic: "The Judiciary",
    learningObjective: "Identify a writ.",
    question: "Which writ commands the production of a detained person before the court?",
    options: ["Mandamus", "Habeas corpus", "Certiorari", "Quo warranto"],
    answer: "Habeas corpus",
    explanation: "'You shall have the body' - tests legality of detention.",
    commonMistake: "Confusing with mandamus.",
  },
  {
    ...mcqBase,
    id: "icse-10-hc-q-mcq-008", component: "History",
    chapterId: "icse-10-hc-his-01", topic: "The Indian National Movement (1857-1917)",
    learningObjective: "Recall the year of the INC foundation.",
    question: "The Indian National Congress was founded in:",
    options: ["1857", "1885", "1905", "1916"],
    answer: "1885",
    explanation: "Founded by A.O. Hume; first session Bombay.",
    commonMistake: "Confusing with the Bengal Partition (1905).",
  },
  {
    ...mcqBase,
    id: "icse-10-hc-q-mcq-009", component: "History",
    chapterId: "icse-10-hc-his-01", topic: "The Indian National Movement (1857-1917)",
    learningObjective: "Identify the leader associated with 'Swaraj is my birthright'.",
    question: "'Swaraj is my birthright and I shall have it' was declared by:",
    options: ["Gokhale", "Tilak", "Naoroji", "Surendranath Banerjee"],
    answer: "Tilak",
    explanation: "Bal Gangadhar Tilak - Assertive Nationalist.",
    commonMistake: "Attributing it to Gokhale.",
  },
  {
    ...mcqBase,
    id: "icse-10-hc-q-mcq-010", component: "History",
    chapterId: "icse-10-hc-his-02", topic: "Mass Phase of the National Movement (1915-1947)",
    learningObjective: "Recall the event that suspended the NCM.",
    question: "The Non-Cooperation Movement was suspended after the:",
    options: ["Jallianwala Bagh tragedy", "Chauri Chaura incident", "Dandi March", "Surat Split"],
    answer: "Chauri Chaura incident",
    explanation: "Violence in February 1922 led Gandhi to suspend the movement.",
    commonMistake: "Choosing Jallianwala Bagh (a cause, not the suspension).",
  },
  {
    ...mcqBase,
    id: "icse-10-hc-q-mcq-011", component: "History",
    chapterId: "icse-10-hc-his-02", topic: "Mass Phase of the National Movement (1915-1947)",
    learningObjective: "Recall the start of the CDM.",
    question: "The Civil Disobedience Movement began with:",
    options: ["The Quit India Resolution", "The Dandi March", "The Lucknow Pact", "The Simon Commission"],
    answer: "The Dandi March",
    explanation: "Salt law broken at Dandi, April 1930.",
    commonMistake: "Confusing with Quit India.",
  },
  {
    ...mcqBase,
    id: "icse-10-hc-q-mcq-012", component: "History",
    chapterId: "icse-10-hc-his-03", topic: "The Contemporary World",
    learningObjective: "Identify the immediate cause of WWI.",
    question: "The immediate cause of the First World War was:",
    options: ["The Treaty of Versailles", "The Sarajevo crisis", "The invasion of Poland", "Pearl Harbour"],
    answer: "The Sarajevo crisis",
    explanation: "Assassination of Archduke Franz Ferdinand, 28 June 1914.",
    commonMistake: "Choosing Versailles (a result of the war).",
  },
  {
    ...mcqBase,
    id: "icse-10-hc-q-mcq-013", component: "History",
    chapterId: "icse-10-hc-his-03", topic: "The Contemporary World",
    learningObjective: "Recall the founding year of the UN.",
    question: "The United Nations was founded in:",
    options: ["1919", "1939", "1945", "1948"],
    answer: "1945",
    explanation: "Founded on 24 October 1945 after WWII.",
    commonMistake: "Choosing 1919 (the League of Nations).",
  },
  {
    ...mcqBase,
    id: "icse-10-hc-q-mcq-014", component: "History",
    chapterId: "icse-10-hc-his-03", topic: "The Contemporary World",
    learningObjective: "Associate UNESCO with its headquarters.",
    question: "UNESCO's headquarters are located in:",
    options: ["New York", "Geneva", "Paris", "The Hague"],
    answer: "Paris",
    explanation: "UNICEF - New York; WHO - Geneva; UNESCO - Paris; ICJ - The Hague.",
    commonMistake: "Mixing the cities.",
  },
];