import type { QuestionMetadata } from "../types";

export const grammarQuestions: QuestionMetadata[] = [
  {
    id: "icse-9-eng-q-gr-001",
    board: "ICSE", class: 9, subject: "English", component: "Language",
    chapterId: "icse-9-eng-lang-gram-01", topic: "Parts of Speech",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Understand",
    learningObjective: "Identify parts of speech in context.",
    source: "original", year: null,
    question: "Identify the part of speech of 'beautifully' in: 'She sang beautifully.'",
    hints: ["Ask: what does it describe — a noun or a verb?"],
    answer: "Adverb.",
    explanation: "It describes the verb 'sang'.",
    commonMistake: "Students call it an adjective because it ends in -ly.",
  },
  {
    id: "icse-9-eng-q-gr-002",
    board: "ICSE", class: 9, subject: "English", component: "Language",
    chapterId: "icse-9-eng-lang-gram-02", topic: "Tenses",
    questionType: "grammar-transformation", difficulty: "medium", marks: 2, bloomLevel: "Apply",
    learningObjective: "Choose correct tense based on time markers.",
    source: "original", year: null,
    question: "Fill in: 'By next December, I ______ (complete) my Class 10 syllabus.'",
    hints: ["Completion by a future point."],
    answer: "will have completed.",
    explanation: "Future perfect for completion by future point.",
    commonMistake: "Using 'will complete' instead.",
  },
  {
    id: "icse-9-eng-q-gr-003",
    board: "ICSE", class: 9, subject: "English", component: "Language",
    chapterId: "icse-9-eng-lang-gram-03", topic: "Subject-Verb Agreement",
    questionType: "mcq", difficulty: "easy", marks: 1, bloomLevel: "Apply",
    learningObjective: "Match verb to subject.",
    source: "original", year: null,
    question: "Choose: 'The number of applicants (has/have) increased.'",
    options: ["has", "have"],
    hints: ["'The number' vs 'a number'."],
    answer: "has",
    explanation: "'The number' is singular.",
    commonMistake: "Choosing 'have' because 'applicants' is plural.",
  },
  {
    id: "icse-9-eng-q-gr-004",
    board: "ICSE", class: 9, subject: "English", component: "Language",
    chapterId: "icse-9-eng-lang-gram-04", topic: "Articles",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Apply",
    learningObjective: "Choose articles based on sound.",
    source: "original", year: null,
    question: "Correct: 'The honesty is a best policy.'",
    hints: ["Abstract noun generally; superlative."],
    answer: "Honesty is the best policy.",
    explanation: "No article for abstract noun generally; 'the' for superlative.",
    commonMistake: "Keeping 'a best'.",
  },
  {
    id: "icse-9-eng-q-gr-005",
    board: "ICSE", class: 9, subject: "English", component: "Language",
    chapterId: "icse-9-eng-lang-gram-10", topic: "Active and Passive Voice",
    questionType: "grammar-transformation", difficulty: "medium", marks: 2, bloomLevel: "Apply",
    learningObjective: "Convert active to passive.",
    source: "original", year: null,
    question: "Change to passive: 'The chef prepared a delicious meal.'",
    hints: ["Object becomes subject."],
    answer: "A delicious meal was prepared by the chef.",
    explanation: "Simple past → was + V3.",
    commonMistake: "Forgetting tense preservation.",
  },
  {
    id: "icse-9-eng-q-gr-006",
    board: "ICSE", class: 9, subject: "English", component: "Language",
    chapterId: "icse-9-eng-lang-gram-11", topic: "Direct and Indirect Speech",
    questionType: "grammar-transformation", difficulty: "medium", marks: 2, bloomLevel: "Apply",
    learningObjective: "Convert direct to indirect speech.",
    source: "original", year: null,
    question: "Change: He said, \"I will come tomorrow.\"",
    hints: ["Shift tense and time words."],
    answer: "He said that he would come the next day.",
    explanation: "Will→would; tomorrow→the next day.",
    commonMistake: "Forgetting tense shift.",
  },
  {
    id: "icse-9-eng-q-gr-007",
    board: "ICSE", class: 9, subject: "English", component: "Language",
    chapterId: "icse-9-eng-lang-gram-14", topic: "Punctuation",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Apply",
    learningObjective: "Correct punctuation errors.",
    source: "original", year: null,
    question: "Correct: 'Its raining, isnt it.'",
    hints: ["Contraction + question mark."],
    answer: "It's raining, isn't it?",
    explanation: "Apostrophe for contraction; question mark.",
    commonMistake: "'Its' without apostrophe.",
  },
];
