import type { QuestionMetadata } from "../types";

export const literatureQuestions: QuestionMetadata[] = [
  {
    id: "icse-9-eng-q-lit-001",
    board: "ICSE", class: 9, subject: "English", component: "Literature",
    chapterId: "icse-9-eng-lit-prose-01-01", topic: "Bonku Babu's Friend",
    questionType: "short", difficulty: "easy", marks: 2, bloomLevel: "Remember",
    learningObjective: "Recall key characters.",
    source: "original", year: null,
    question: "Who was Ang? Where did he come from?",
    hints: ["Alien from Craneus."],
    answer: "Ang was an alien from the planet Craneus, 833 years old.",
    explanation: "Character identification.",
    commonMistake: "Confusing with a human character.",
  },
  {
    id: "icse-9-eng-q-lit-002",
    board: "ICSE", class: 9, subject: "English", component: "Literature",
    chapterId: "icse-9-eng-lit-prose-01-02", topic: "Oliver Asks for More",
    questionType: "analytical", difficulty: "hard", marks: 6, bloomLevel: "Analyse",
    learningObjective: "Analyse Dickens's social critique.",
    source: "original", year: null,
    question: "How does Dickens expose the cruelty of the workhouse system?",
    hints: ["Cite physical, psychological, bureaucratic cruelty."],
    answer: "Through systematic starvation, brutal punishment, and bureaucratic indifference; Dickens critiques the 1834 Poor Law.",
    explanation: "Multi-layered analysis.",
    commonMistake: "Treating Bumble as the only villain.",
  },
  {
    id: "icse-9-eng-q-lit-003",
    board: "ICSE", class: 9, subject: "English", component: "Literature",
    chapterId: "icse-9-eng-lit-prose-01-04", topic: "The Home-coming",
    questionType: "extract-based", difficulty: "hard", marks: 6, bloomLevel: "Analyse",
    learningObjective: "Analyse significance of extract.",
    source: "original", year: null,
    question: "Analyse: 'Uncle, have you brought my mother?'",
    hints: ["Speaker, context, significance."],
    answer: "Phatik's deathbed question reveals his deep longing for love despite neglect — the emotional climax of the story.",
    explanation: "Extract analysis.",
    commonMistake: "Not connecting to theme of emotional neglect.",
  },
  {
    id: "icse-9-eng-q-lit-004",
    board: "ICSE", class: 9, subject: "English", component: "Literature",
    chapterId: "icse-9-eng-lit-drama-01", topic: "Julius Caesar",
    questionType: "extract-based", difficulty: "hard", marks: 6, bloomLevel: "Analyse",
    learningObjective: "Analyse Brutus's soliloquy.",
    source: "original", year: null,
    question: "Analyse Brutus's soliloquy in Act II, Scene 1.",
    hints: ["Context → meaning → significance."],
    answer: "Brutus decides Caesar must die not for what he has done but for what he might become — the moral turning point of the play.",
    explanation: "Extract analysis with thematic significance.",
    commonMistake: "Confusing Brutus with Cassius's motivation.",
  },
  {
    id: "icse-9-eng-q-lit-005",
    board: "ICSE", class: 9, subject: "English", component: "Literature",
    chapterId: "icse-9-eng-lit-poetry-01-05", topic: "A Work of Artifice",
    questionType: "analytical", difficulty: "medium", marks: 6, bloomLevel: "Analyse",
    learningObjective: "Analyse metaphor.",
    source: "original", year: null,
    question: "How does Piercy use the bonsai as a metaphor?",
    hints: ["Pruning, pot, gardener, 'eighty feet'."],
    answer: "Bonsai = women whose potential is deliberately limited by patriarchy (gardener).",
    explanation: "Extended metaphor analysis.",
    commonMistake: "Not linking to feminist critique.",
  },
];
